import { LineEdit, VerticalBox } from "std-widgets.slint";

export component InputField inherits VerticalBox {
    in property <string> label;
    in property <string> value;
    in property <string> error;
    in property <bool> editable: true;
    callback edited(string);
    spacing: 4px;
    Text {
        text: root.label;
        wrap: word-wrap;
    }

    LineEdit {
        text: root.value;
        enabled: root.editable;
        edited(value) => { root.edited(value); }
    }

    if root.error != "": Text {
        text: root.error;
        color: #e77b73;
        wrap: word-wrap;
    }
}
